### ISSUE TITLE
When I used `php_strip_whitespace` to compress my PHP code, this library didn't work as expected.

### ISSUE THREAD

**Issue by dreamncn** [laravel/serializable-closure#72]
### Serializable Closure Version

1.3.1

### PHP Version

8.2.0

### Description

When I used `php_strip_whitespace` to compress my PHP code, this library didn't work as expected. Is a bug?

### Steps To Reproduce

1. I defined a function `go` to use this Library.

```php
function go(Closure $function, int $timeout = 300)
{
    if (App::$cli) return null;
    return MyCustomClass::start($function, $timeout);
}
```

2. In this method `start`, I used

```php
serialize(new SerializableClosure($function));
```

and I saved it to a cache file.

3. When I used the function `go`:

   ```php
    public static function start($bool): void
       {
           if ($bool) {
              go(function () {
                      //some functions...
                   }, 0);
           } else {
               Log::record("Error");
           }
       }
   ```

   

4. If I used `php_strip_whitespace` to compress my code, it means my code will display like this:

   ```php
    public static function start($bool): void{if($bool){go(function(){}, 0);} else {Log::record("Error");}}
   ```

   It will cache the code:

   ```php
   if($bool){go(function(){}, 0);} else {Log::record("Error");
   ```

   But if I don't compress my code, it will cache the code:

   ```php
   function(){}
   ```

   When only uncompressed,  it meet expectations. Is this a bug?

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by dreamncn** [comment]
Embarrassingly, when I tried to create a demo, I found that it worked normally. Obviously, part of my code affected it.
I will temporarily close the issue, and then reopen the issue after I find out the problem.
